Comprehensions & core object changes
fedora-python/portingguide pull request #21
Opened 2017-04-28 15:12 UTC by encukou

- Finish up Comprehensions
- Write the penultimate chapter

2017-04-28 15:45 UTC, hroncok commented
I'm not 100 % sure with my latest commit, but I think "since" indicates a "perfect" tense. In this case I went with past perfect, because everything with Python 2 is in the past and Python 3 is the present. @torsava is a good candidate to say if I'm right or wrong.

2017-04-28 15:56 UTC, hroncok commented on source/core-obj-misc.rst
> +i.e. to provide an implementation for :func:`bool`.
The link here doesn't work.

```rst
:class:`bool`
```

works, but removes the parenthesis and reads bad. Is it possible to fix the link but force the parenthesis? (I'm not that good with RST.)

2017-04-28 16:00 UTC, hroncok requested changes
The bool thingy. Also, please check my commits, especially the one I've sent comment about.

2017-04-30 07:52 UTC, encukou commented on source/core-obj-misc.rst
> +i.e. to provide an implementation for :func:`bool`.
ReST (Sphinx, actually) has syntax for completely custom link text, so I went with that:

    :class:`bool() <bool>`

2017-04-30 07:55 UTC, encukou commented
As for the tenses, I trust your judgement. I didn't learn English in school, so I mostly don't care about language technicalities. But big thanks for your attention to detail!

2017-04-30 07:55 UTC, merged

2017-05-02 09:21 UTC, torsava commented
@hroncok:
> I'm not 100 % sure with my latest commit, but I think "since" indicates a "perfect" tense. In this case I went with past perfect, because everything with Python 2 is in the past and Python 3 is the present. @torsava  is a good candidate to say if I'm right or wrong.

I believe you are right. Good catch!