Handle encoding in text about execfile()
fedora-python/portingguide pull request #29
Opened 2018-02-12 12:25 UTC by encukou

Fixes: https://github.com/fedora-python/portingguide/issues/25

Unfortunately, tokenize.open() is not available in Python 2, so we
can't just use it here. But hopefully, code that needs this is
vanishingly rare, so a comment will suffice.

2018-02-22 16:27 UTC, encukou commented
Lumír, does this make sense to you?

2018-02-22 17:31 UTC, hroncok commented on source/builtins.rst
> +    import tokenize
Not used.

2018-02-23 07:30 UTC, frenzymadness commented on source/builtins.rst
> +        with open(filename, encoding='utf-8') as f:
If you want to use `encoding` kwarg in `open()` function in Python 2, you have to import `open()` function from `io` module first. Default `open()` function in Python 2 doesn't support that.

2018-02-23 07:31 UTC, frenzymadness requested changes
Just remove unused import and add `from io import open` and it'll be ready to merge.

2018-02-23 10:56 UTC, encukou commented on source/builtins.rst
> +
I also added this note on io.open.

2018-02-23 10:57 UTC, encukou commented
Oops! Changed.

2018-02-23 12:30 UTC, frenzymadness commented
Now it looks good to me. Good job!

2018-02-23 12:30 UTC, frenzymadness approved these changes

2018-02-23 12:30 UTC, merged